DOMAIN = "energy_cost"

PLATFORMS = ["sensor"]

FIELD_NAME = "name"

FIELD_POWER = "power"
FIELD_PUN_MODE = "pun_mode"

FIELD_RATE_MODE = "rate_mode"
FIELD_RATE_MODE_MONO = "rate_mode_mono"
FIELD_RATE_MODE_FLEX = "rate_mode_flex"

FIELD_MONO_RATE = "mono_rate"
FIELD_F1_RATE = "f1_rate"
FIELD_F2_RATE = "f2_rate"
FIELD_F3_RATE = "f3_rate"
FIELD_FIXED_FEE = "fixed_fee"
FIELD_VAT_FEE = "vat_fee"

FIELD_POWER_ENTITY = "power_entity"
FIELD_PUN_ENTITY = "pun_entity"
FIELD_CURRENT_RATE_ENTITY = "current_rate_entity"

DISPBT = 0.102592
TRASPORTO_QUOTA_FISSA = 1.9
TRASPORTO_QUOTA_POTENZA = 2.09
UC6_CONTINUITA_FISSO = 0.016567
UC6_CONTINUITA = 0.00007
CORRISPETTIVO_CAPACITA = 0.004275
DISPACCIAMENTO = 0.0098
TRASPORTO_QUOTA_ENERGIA = 0.01189
UC3_COPERTURA_SQUILIBRI = 0.00156
ARIM = 0.001645
ASOS = 0.029677
IMPOSTA_ERARIALE = 0.0227