DOMAIN = "energy_cost"

PLATFORMS = ["sensor", "number"]

FIELD_NAME = "name"

FIELD_POWER = "power"
FIELD_PUN_MODE = "pun_mode"

FIELD_RATE_MODE = "rate_mode"
FIELD_RATE_MODE_MONO = "rate_mode_mono"
FIELD_RATE_MODE_FLEX = "rate_mode_flex"

FIELD_MONO_RATE = "mono_rate"
FIELD_F1_RATE = "f1_rate"
FIELD_F2_RATE = "f2_rate"
FIELD_F3_RATE = "f3_rate"
FIELD_FIXED_FEE = "fixed_fee"
FIELD_VAT_FEE = "vat_fee"

FIELD_POWER_ENTITY = "power_entity"
FIELD_PUN_ENTITY = "pun_entity"
FIELD_CURRENT_RATE_ENTITY = "current_rate_entity"

DISPBT = 0.1099
TRASPORTO_QUOTA_FISSA = 1.84
TRASPORTO_QUOTA_POTENZA = 1.85
UC6_CONTINUITA_FISSO = 0.016567
UC6_CONTINUITA = 0.00007
CORRISPETTIVO_CAPACITA = 0.002995
DISPACCIAMENTO = 0.007707
TRASPORTO_QUOTA_ENERGIA = 0.010570
UC3_COPERTURA_SQUILIBRI = 0.001560
ARIM = 0.008828
ASOS = 0.029809
IMPOSTA_ERARIALE = 0.0227